export enum AlbumsActionTypes {
  ERROR = "ERROR",
  FETCH_PROFILE = "FETCH_PROFILE",
  FETCH_ALBUMS = "FETCH_ALBUMS",
  SET_LOADING = "SET_LOADING",
  FETCH_NUM_PHOTOS = "FETCH_NUM_PHOTOS",
}

export enum AlbumActionType {
  ERROR = "ERROR",
  SET_LOADING = "SET_LOADING",
  FETCH_ALBUM = "FETCH_ALBUM",
  FETCH_ALBUM_PHOTOS = "FETCH_ALBUM_PHOTOS",
}

export enum PhotoActionTypes {
  ERROR = "ERROR",
  SET_LOADING = "SET_LOADING",
  FETCH_COMMENTS = "FETCH_COMMENTS",
  FETCH_PHOTO = "FETCH_PHOTO",
  ADD_COMMENT = "ADD_COMMENT",
  UPDATE_PHOTO = "UPDATE_PHOTO",
  FETCH_FAVORITE_STATUS = "FETCH_FAVORITE_STATUS",
  UPDATE_FAVORITE_STATUS = "UPDATE_FAVORITE_STATUS",
}

export enum FavoritesActionType {
  ERROR = "ERROR",
  SET_LOADING = "SET_LOADING",
  FETCH_PHOTOS = "FETCH_PHOTOS",
  REMOVE_FAVORITE = "REMOVE_FAVORITE",
}
